language: scala

jdk:
  - oraclejdk8

scala:
  - 2.11.8

sudo: false

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/

# Scala-JS 0.6.13 and later uses NodeJS for scala-js testing
install:
  - . $HOME/.nvm/nvm.sh
  - nvm install stable
  - nvm use stable
  - npm install
  - npm install jsdom

script:
  # Your normal script
  - sbt -J-XX:ReservedCodeCacheSize=256M test

  # Tricks to avoid unnecessary cache updates
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm
